# Generated by Django 5.0.6 on 2024-07-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_create_at_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='catigory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.catigory', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='car',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.maker', verbose_name='name'),
        ),
    ]
